version: '2'
services:
  web:
    build: .
    ports:
     - "4567:4567"
    volumes:
     - .:/app
    depends_on:
     - redis
  redis:
    image: redis

# to run this:
#
#   # (alias)
#
#   alias dc=docker-compose
#
#   # run
#
#   dc build && dc up
#
##
